# Generated by Django 3.2.5 on 2023-01-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiprompt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='body',
            new_name='prompt',
        ),
    ]
