# Generated by Django 4.1 on 2023-01-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiprompt", "0003_remove_prompt_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt", old_name="prompt", new_name="prompts",
        ),
    ]
