# Generated by Django 4.1 on 2023-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourjournal", "0002_remove_entry_id_entry_prompt_ptr_alter_entry_body"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="prompt_ptr",),
        migrations.AddField(
            model_name="entry",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entry", name="prompt", field=models.TextField(default="trey"),
        ),
    ]
