# Generated by Django 4.1 on 2023-01-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yourjournal", "0003_remove_entry_prompt_ptr_entry_id_entry_prompt"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="body",),
    ]
