# Generated by Django 4.1 on 2023-01-08 22:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yourjournal", "0004_remove_entry_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
