# Generated by Django 4.1 on 2023-01-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yourjournal", "0006_rename_prompt_entry_prompts_remove_entry_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry", old_name="prompts", new_name="write",
        ),
    ]
