# Generated by Django 4.1 on 2023-01-16 17:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yourjournal", "0007_rename_prompts_entry_write"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
